#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=50gb,walltime=10:00:00
#PBS -N pRF
#PBS -V

#export MAXMEM=19000000
fmri=$(jq -r .fmri config.json)
stim=$(jq -r .stim config.json)
fsdir=$(jq -r .output config.json)
#mask=$(jq -r .mask config.json)
if [ ! -f jq -r .mask config.json ]; then
  time singularity exec -e docker://brainlife/freesurfer:6.0.1 mri_convert ${fsdir}/mri/T1.mgz ${fsdir}/mri/T1.nii.gz
  time singularity exec -e docker://brainlife/fsl:6.0.1 ./create_mask.sh $fsdir $fmri
fi

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

#time singularity exec -e docker://brainlife/afni:16.3.0 ./align.sh

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.1 ./create_vtks.sh $fsdir
#time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.1 ./replace_vtks.sh
